// INCLUDE HEADER FILES NEEDED BY YOUR PROGRAM
// SOME LIBRARY FUNCTIONALITY MAY BE RESTRICTED
// DEFINE ANY FUNCTION NEEDED
// FUNCTION SIGNATURE BEGINS, THIS FUNCTION IS REQUIRED
boundedarray* cellCompete(int* states, int days)
{
    // WRITE YOUR CODE HERE
}
// FUNCTION SIGNATURE ENDS