#include "realq2.h"

// INCLUDE HEADER FILES NEEDED BY YOUR PROGRAM
// SOME LIBRARY FUNCTIONALITY MAY BE RESTRICTED
// DEFINE ANY FUNCTION NEEDED
// FUNCTION SIGNATURE BEGINS, THIS FUNCTION IS REQUIRED
boundedarray* lengthEachScene(charboundedarray* inputList)
{
    // WRITE YOUR CODE HERE
}
// FUNCTION SIGNATURE ENDS