// INCLUDE HEADER FILES NEEDED BY YOUR PROGRAM
// SOME LIBRARY FUNCTIONALITY MAY BE RESTRICTED
// DEFINE ANY FUNCTION NEEDED
// FUNCTION SIGNATURE BEGINS, THIS FUNCTION IS REQUIRED
int generalizedGCD(int num, int* arr)
{
    // WRITE YOUR CODE HERE
}
// FUNCTION SIGNATURE ENDS